# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "is4boajPZtXwGVlCDP7c/Ll1k53pWVrU5CGHtSb/OOp9o6vJfiSMX9s8V5V/M1IXve7Gn6oRG7nlqW2ClXUVadZqJLQsT6qAX0daVE7bT4G+0dOw46TPrPieeeCPvXkjUrwgfcTUB6WsBhtwHZNHExzl4pbc1j9svuxfOxVZ50tqvHSdL0d9WRrDQpHdzigi7MOqP2J1VpwzPZL/5n5HyX1UKWmOJicZfPLYsX0lVAn4dRQPQZaiz6/T2wb00iNjlNCTPqZGT6lfxUn7u6Bp/zPNvbJjdkwAwLBx9St9HnTjtaldjMdKudct4s/zEw3AR50eGiEJbMGd/8hJHx5wOaPrIMSW8ybePPilYTQ8sscGCr8XLt6UEEp8H5fF3UHQmpLo6lY4H3AjWOFKwsfhj3IoFWphZNtlR/L8QbpwPyemRgqrQL6+PfDJvHsBsDTTGwolCq8FNDD+Rb6PSh/aPBEwKGWl6vepxj4Egh58DypsGjr/7pOwN/bDTAHO7x/BIRC7cgrJf7nRxgvGQ74fPWSgOcSgYEHab3stTi0hqKhFC5vbaBsz/ikatGAxGTfhwGInUNI2Zv+ZsTjJtdga15I1pbFiiuLCosXevchxXK1h3A3j0T/r2Dz4DH35sgUai+lgmXYFDChw5Fzo3BHFyjBiQR+oEeMl+So3MOCY2cE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
