# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "is4boajPZtXwGVlCDP7c/Ll1k53pWVrU5CGHtSb/OOp9o6vJfiSMX9s8V5V/M1IXve7Gn6oRG7nlqW2ClXUVadZqJLQsT6qAX0daVE7bT4G+0dOw46TPrPieeeCPvXkjUrwgfcTUB6WsBhtwHZNHExzl4pbc1j9svuxfOxVZ50tqvHSdL0d9WRrDQpHdzigi7MOqP2J1VpwzPZL/5n5HyX1UKWmOJicZfPLYsX0lVAn4dRQPQZaiz6/T2wb00iNjlNCTPqZGT6lfxUn7u6Bp/zPNvbJjdkwAwLBx9St9HnTjtaldjMdKudct4s/zEw3AR50eGiEJbMGd/8hJHx5wOaPrIMSW8ybePPilYTQ8sscGCr8XLt6UEEp8H5fF3UHQmpLo6lY4H3AjWOFKwsfhj3IoFWphZNtlR/L8QbpwPyemRgqrQL6+PfDJvHsBsDTTGwolCq8FNDD+Rb6PSh/aPBEwKGWl6vepxj4Egh58DypsGjr/7pOwN/bDTAHO7x/BIRC7cgrJf7nRxgvGQ74fPWSgOcSgYEHab3stTi0hqKhFC5vbaBsz/ikatGAxGTfhwGInUNI2Zv+ZsTjJtdga15I1pbFiiuLCosXevchxXK1h3A3j0T/r2Dz4DH35sgUai+lgmXYFDChw5Fzo3BHFyjBiQR+oEeMl+So3MOCY2cE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
