appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: is4boajPZtXwGVlCDP7c/Ll1k53pWVrU5CGHtSb/OOp9o6vJfiSMX9s8V5V/M1IXve7Gn6oRG7nlqW2ClXUVadZqJLQsT6qAX0daVE7bT4G+0dOw46TPrPieeeCPvXkjUrwgfcTUB6WsBhtwHZNHExzl4pbc1j9svuxfOxVZ50tqvHSdL0d9WRrDQpHdzigi7MOqP2J1VpwzPZL/5n5HyX1UKWmOJicZfPLYsX0lVAn4dRQPQZaiz6/T2wb00iNjlNCTPqZGT6lfxUn7u6Bp/zPNvbJjdkwAwLBx9St9HnTjtaldjMdKudct4s/zEw3AR50eGiEJbMGd/8hJHx5wOaPrIMSW8ybePPilYTQ8sscGCr8XLt6UEEp8H5fF3UHQmpLo6lY4H3AjWOFKwsfhj3IoFWphZNtlR/L8QbpwPyemRgqrQL6+PfDJvHsBsDTTGwolCq8FNDD+Rb6PSh/aPBEwKGWl6vepxj4Egh58DypsGjr/7pOwN/bDTAHO7x/BIRC7cgrJf7nRxgvGQ74fPWSgOcSgYEHab3stTi0hqKhFC5vbaBsz/ikatGAxGTfhwGInUNI2Zv+ZsTjJtdga15I1pbFiiuLCosXevchxXK1h3A3j0T/r2Dz4DH35sgUai+lgmXYFDChw5Fzo3BHFyjBiQR+oEeMl+So3MOCY2cE=}
bot:
  automerge: true
