travis:
  secure:
    BINSTAR_TOKEN: B1tErbouH306lCEXu0oBH6qhVvhx3Mb3bh4E3pZ3JVKkLMvpy9AR+GHt0KKN3KqjCvCpp+nuHkzzS0JWtou3WLrVLkA30IvlNUP1ZRkdTlrEH0W22kzyTBxl2JlOKuEhzrLtWwH4E+zh3EVebdRlEI65c7mgzDcRiCidSj1ntpmJYBB8yq7lk2uSwTsSMyLqmOHPLbWm12O0418rre1gwg2MUJc8H/cjKUv8cPSwxCP1u6eSKWZiElsGGpCwPCuAnn/UzcIlkTg42GRnpPmdb6h6meyP5bHpcSpXPdDBnHzybcUTdIsBFg964MwyMGZDavSL9cp8EMCSHN78lHLDeeedrHkz9P75hX3ujYoQFLUAOmmtufpFtNze+RxwgkOCFMOKqf1DMPeBXZkMbagCEOpvS1F7RM2NMaenFcBWDAj0QzR82OrJ014fQfX9Izpx8jmRG5856F+UGO+YPnBZKkswMIflXchrNlyZiIcqeX810BUpiEe3Pi5ohhtNdsPxlSDUFVMkVluFzKwnGRytpP/hZUQ5JxPHHq9F8YSQRfVZ7w+s+vkpA5iTSXoKsLblfI7QuVcnngR9S+CFUKZKPBI9Bb08B+PJzi/mmlkJam1jOS+OCBgXX8ZHQ1u2d1L5x6/JL6xeVbWrb/PdlFZpzfatDO6wm7wKAKEDZUGpp1g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
